version: '3.1'
services:
  minio:
    image: quay.io/minio/minio
    networks:
      - airflow
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
       - ${PWD}/include/minio:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    restart: always
    env_file: .env

  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8501:8501
      - 8502:8502
    networks:
      - airflow

  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow



networks:
  airflow:
    driver: bridge